# Use to deploy iplink-daemon on kube
apiVersion: v1
kind: Namespace
metadata:
  name: iplink-daemon
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iplink-daemon 
  namespace: iplink-daemon
  labels:
    app: iplink-daemon
spec:
  selector:
    matchLabels:
      app: iplink-daemon
  template:
    metadata:
      labels:
        app: iplink-daemon
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iplink-daemon
        image: ghcr.io/backchristoffer/iplink-daemon:latest
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 0