name: build and push iplink

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to github
      run: docker build . --tag iplink-daemon:latest
    - name: Tag image
      run: docker image tag iplink-daemon:latest ghcr.io/backchristoffer/iplink-daemon:latest
    - name: Push image to github
      run: docker image push ghcr.io/backchristoffer/iplink-daemon:latest